export const ROLE_LIST = {
	ADMIN: "ADMIN",
	SUPERVISOR: "SUPERVISOR",
	MEMBER: "MEMBER",
	enumValues: ["ADMIN", "SUPERVISOR", "MEMBER"]
} as const;

export const TOKEN_LIST = {
	PASSWORD_RESET: "PASSWORD_RESET",
	EMAIL_VERIFICATION: "EMAIL_VERIFICATION",
	LOGIN_OTP: "LOGIN_OTP",
	enumValues: ["PASSWORD_RESET", "EMAIL_VERIFICATION", "LOGIN_OTP"]
} as const;
