// AUTO‑GENERATED by update‑schema.mjs. Do not edit by hand.

import * as EmailSchema from "@/models/drizzle/email.model";
import * as EmailTemplateSchema from "@/models/drizzle/emailTemplate.model";

const schema = {
	...EmailSchema,
	...EmailTemplateSchema
};

export default schema;
